### ISSUE TITLE
Snippets don't work in math environment

### ISSUE THREAD

**Issue by Rdbllx** [area/language-latex#47] opened 2015-08-23 17:06 UTC
Hi, I tried to use snippets in a math environment like this one $$ or \[ \] but it doesn't work.
Is it normal ? 
Thank's in advance for your answers

**Comment by Rdbllx** [comment] 2015-08-28 21:14
I need some help please, can someone help me or if someone knows how to fix it ?

**Comment by Rdbllx** [comment] 2015-10-18 15:49
Could someone answer please ?

**Comment by area** [comment] 2016-10-02 14:00
Dupe of #56 which, while this one came first, has a little more info.

**Closed by area** 2016-10-02 14:00 UTC
