### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by kexanie** [area/language-latex#25] opened 2015-04-05 04:31 UTC
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (/opt/atom/resources/app/src/package.js:565:9)
<unknown> (/opt/atom/resources/app/src/package.js:187:43)
```

**Comment by thorade** [comment] 2015-04-08 08:38
Exact duplicate of #22

**Closed** 2015-04-13 15:47 UTC
