### ISSUE TITLE
About using snippets

### ISSUE THREAD

**Issue by sumandoc** [area/language-latex#130] opened 2017-06-21 07:02 UTC
I am not being able to use snippets in the CSON file.

These are the ones.

```cson
'.text.tex.latex .string.other.math':
  'math italic':
    'prefix': 'it'
    'body': '\\\\mathit{$1}$0'
  'math boldface':
    'prefix': 'bf'
    'body': '\\\\mathbf{$1}$0'
  'math blackboard':
    'prefix': 'bb'
    'body': '\\\\mathbb{$1}$0'
  'math roman':
    'prefix': 'rm'
    'body': '\\\\mathrm{$1}$0'
  'math sans-serif':
    'prefix': 'sf'
    'body': '\\\\mathsf{$1}$0'
  'math calligraphy':
    'prefix': 'cal'
    'body': '\\\\mathcal{$1}$0'
  'fraction':
    'prefix': 'frac'
    'body': '\\\\frac{$1}{$2}$0'
  'aligned':
    'prefix': 'aligned'
    'body': '\\\\begin{aligned}$1\n\t$0\n\\\\end{aligned}'
  'gathered':
    'prefix': 'gathered'
    'body': '\\\\begin{gathered}$1\n\t$0\n\\\\end{gathered}'
  'matrix':
    'prefix': 'matrix'
    'body': '\\\\begin{$1matrix$2}$3\n\t$0\n\\\\end{$1matrix$2}'

# Beamer
'.text.tex.latex.beamer':
  'Frame':
    'prefix': 'frame'
    'body': '\\\\begin{frame}[t]{${1:title}}\n\t${2:body}\n\\\\end{frame}\n%--- Next Frame ---%'
  'Columns':
    'prefix': 'cols'
    'body': '\\\\begin{columns}\n\\\\begin{column}[T]{$1cm}\n$3\n\\\\end{column}\n\\\\hfill\n\\\\begin{column}[T]{$2cm}\n\n\\\\end{column}\n\\\\end{columns}\n'


# other
'.text.tex.latex .meta.function.environment.list':
  '\\\\item[description]':
    'prefix': 'itd'
    'body': '\\\\item[${1:description}] ${0:item}'
```

How will I be able to use those snippets as well.

Regards,

**Comment by Aerijo** [comment] 2017-07-17 06:52
Where are you trying to use them? 

It looks like the first ones only work in a regular block of text or in a math scope. Check the scope by using the command <kbd>Cmd</kbd> + <kbd>Alt</kbd> + <kbd>p</kbd> (Mac; don't know Win/Linux alternative aside from Dev console).

**Comment by Aerijo** [comment] 2017-07-22 07:08
New information has come to light: snippets don't work in string environments (which is what this packages scopes mathmode to). 

This means the solution, short of a major overhaul on this package (and all the packages that rely on this one; think spell check, chktex, etc.), would have to be done by the autocomplete-snippets package. I believe a solution is coming soon, but I wouldn't hold my breath: I don't know how active the people managing that package are.

**Comment by yudai-nkt** [comment] 2017-08-07 12:10
Snippets do work in math mode, but auto-completion doesn't seem to work.

Could you elaborate what's the problem you are facing with?

**Comment by yudai-nkt** [comment] 2017-08-08 15:09
I still can't reproduce the latter two problem, but does #137 fix the math snippet problem, @sumandoc?

**Comment by Aerijo** [comment] 2018-01-19 02:06
It seems pretty clear that the snippets _are_ working, but they do not appear in an autocomplete popup menu.

![kapture 2018-01-19 at 11 45 45](https://user-images.githubusercontent.com/22167388/35130827-9b2946e6-fd0e-11e7-900a-d72eafabf043.gif)

This behaviour is linked to https://github.com/atom/autocomplete-snippets/issues/63, which is attempted to be fixed by https://github.com/atom/autocomplete-snippets/pull/77.  You should watch those issues to be notified of a resolution. Basically, `autocomplete-snippets` is what links snippets to autocomplete, and `autocomplete-snippets` is disabled for string scopes. yudai-nkt's #137 solution should work, but will only come out with version 2 of this package.

Additionally, I also cannot reproduce any issues with the beamer snippet (which requires the language grammar to be `LaTeX Beamer` in the selection menu) or the item snippet. Both of those also appeared in the autocomplete popup menu.

@sumandoc If I misunderstood anything, feel free to reopen this issue and clarify.

**Closed by Aerijo** 2018-01-19 02:06 UTC
Labels: need info
