### ISSUE TITLE
Syntax highlighting stops working on lines above a certain length

### ISSUE THREAD

**Issue by johncoxon** [area/language-latex#173] opened 2018-02-28 17:08 UTC
### Prerequisites
- [X] Put an `X` in this box if you have done the following:
  - Ensured the issue has not already been raised
  - Ensured the issue is caused by this package
  - Run `atom --safe`, activated this package, and the issue persisted

### Steps to reproduce & Minimum working example
```
The Magnetospheric Multiscale (MMS) mission is a four-spacecraft constellation mission operated by NASA. It was launched on 12 March 2015 into an equatorial orbit around Earth with a perigee of $0.5R_E$ and an apogee of $11R_E$, designed such that the spacecraft spends most of its time in the magnetosheath and magnetopause \citep{Burch2016, Tooley2016, Fuselier2016}. Each of the constituent spacecraft has an identical instrument suite; for the purposes of this paper, we will employ magnetic field data from the Fluxgate Magnetometer \citep[FGM,][]{Russell2016} and DC electric field data from the Axial Double Probe \citep[ADP,][]{Ergun2016} and Spin plane Double Probes \citep[SDP,][]{Lindqvist2016}. These instruments are all part of the FIELDS experiment \citep{Torbert2016}. Additionally, we use plasma moments from the Fast Plasma Instrument \citep[FPI,][]{Pollock2016}.
```

#### Expected behaviour

It should highlight the whole passage correctly.

#### Actual behaviour

It does not highlight the passage after the `\citep` command immediately before `[SDP,]`. Inserting a line break before this `\citep` command restores the highlighting functionality.

**Comment by yudai-nkt** [comment] 2018-02-28 23:04
I guess this is a duplicate of #139. Please reopen and correct me if I'm wrong.

**Closed by yudai-nkt** 2018-02-28 23:04 UTC
