### ISSUE TITLE
Quotation marks cause atom editor format to go wrong

### ISSUE THREAD

**Issue by audioplastic** [area/language-latex#129] opened 2017-05-19 12:51 UTC
The following, for example . . 

    \noindent{\Huge``}

Is perfectly valid latex, but causes all text in the remainder of the document to turn green

**Comment by Aerijo** [comment] 2017-07-17 07:10
This is because `` is matched as the start of a quote, which is only ended by ''. I'm not sure what the best solution is, other than not having such a strange construction, but perhaps use \textquotedblleft for the quote symbols. Note that it eats whitespace, so an unbreaking space may be necessary.

Having said that, I don't think quoted text should be scoped at all, given that LaTeX is about typesetting language and there are all sorts of constructions with quote marks in English.

**Comment by Aerijo** [comment] 2017-08-04 13:29
Subscribe to https://github.com/area/language-latex/pull/96 and/or https://github.com/area/language-latex/issues/61 for updates, please close this issue as it is a duplicate of these.

**Comment by yudai-nkt** [comment] 2017-08-07 11:26
Should be closed by #96.

**Closed by yudai-nkt** 2017-08-07 11:26 UTC
