### ISSUE TITLE
language-latex causes atom to crash

### ISSUE THREAD

**Issue by CarlosEvo** [area/language-latex#153] opened 2017-10-11 06:19 UTC
Atom editor has been crashing recently due to this package. It appeared that whenever I tried to an extra line in a latex file by hitting `return`, the editor crashed with no log of error in developer mode.

**Comment by Aerijo** [comment] 2017-10-11 09:30
(Un?)fortunately, this does not happen with my installation. I need more details, such as OS, attempts to fix, etc. Until then, I can't help.

**Comment by CarlosEvo** [comment] 2017-10-11 16:31
@Aerijo Sorry I was driven slightly mad last night.

So I have been using the latest atom on macOS.

After it started to crash, I tried to start atom by `atom --safe` and it stops crashing when editing `.tex` file.

I also checked the developer log before hand, but no error regarding `language-latex` showed up.

After starting atom again, I disabled the package, and it stopped crashing.

Somehow after I re-enabled it, atom stopped crashing so far. I have no idea what happened...

**Comment by Aerijo** [comment] 2017-10-14 04:54
If it happens again, feel free to reopen this with more information about what causes it (a list of packages would also help). Until then, I'll close this as you indicate the issue has gone away.

**Closed by Aerijo** 2017-10-14 04:54 UTC
Labels: need info

**Comment by CarlosEvo** [comment] 2017-11-18 23:12
@Aerijo I found what user actions causes the crash:

Pressing `return` after a right bracket `}`.

Say, for example, I press return right after a `\paragraph{}`, the window freezes and crashes. The operation can be avoided, but still pretty annoying if encountered.

Attached is part of the crash log (which I finally know where to find):

```
Process:               Atom Helper [22789]
Path:                  /Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper
Identifier:            com.github.atom.helper
Version:               1.22.1 (1.22.1)
Code Type:             X86-64 (Native)
Parent Process:        Atom [335]
Responsible:           Atom [335]
User ID:               502

Date/Time:             2017-11-18 15:05:37.761 -0800
OS Version:            Mac OS X 10.13.1 (17B48)
Report Version:        12
Anonymous UUID:        BBBFD8A8-7049-8CB6-6DC8-42C874290DE8

Sleep/Wake UUID:       E636B3F6-F1CD-458D-9782-021073579482

Time Awake Since Boot: 3400 seconds
Time Since Wake:       2700 seconds

System Integrity Protection: disabled

Crashed Thread:        0  CrRendererMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00007fe07a309c50

VM Regions Near 0x7fe07a309c50:
    MALLOC_TINY            00007fde79f00000-00007fde7a400000 [ 5120K] rw-/rwx SM=PRV  
--> 
    STACK GUARD            00007ffee8941000-00007ffeec141000 [ 56.0M] ---/rwx SM=NUL  stack guard for thread 0

Thread 0 Crashed:: CrRendererMain  Dispatch queue: com.apple.main-thread
0   ???                           	0x000000010d0b49f1 0 + 4513810929
1   ???                           	0x00007fe07a309c50 0 + 140602099407952
```

**Comment by Aerijo** [comment] 2017-11-26 03:12
@CarlosEvo This issue still doesn't happen for me (tried it with `\paragraph{hello world}` + `return`). Maybe try deleting and reinstalling this package and see if that helps. 

It could be caused by some other package, like an autocompleter. This could be why pressing `return` triggers the crash. The only other possible cause I can think of is if it's a large file. If possible, maybe try walking me through the steps to recreate it (with text for me to copy and paste).
