### ISSUE TITLE
highlighting stops working in long lines

### ISSUE THREAD

**Issue by rammmiro** [area/language-latex#179] opened 2018-04-09 12:16 UTC
### Description
Syntax highlighting stops working in long lines.

### Steps to reproduce & Minimum working example
An example .tex file is:

```
\documentclass{article}
\begin{document}
    Here \emph{e}, \emph{e}, \emph{e}, \emph{e}, \emph{e}, \emph{e}, \emph{e}, \emph{e}, \emph{e}, \emph{e}, \emph{e}, \emph{e}, \emph{e}, \emph{e}, \emph{e}, \emph{e}, \emph{e} and \emph{e}.
\end{document}
```

#### Expected behaviour
I think this is a correct example and everything should be normal.

#### Actual behaviour
Syntax highlighting is broken.
<img width="400" alt="example broken syntax highlighting" src="https://user-images.githubusercontent.com/32325306/38496986-c8ee27f6-3bff-11e8-87e1-57eff29be88d.png">

After this point nothing works as expected, and I think this might be a bug.

**Comment by Aerijo** [comment] 2018-04-09 12:18
Duplicate of #139.

Please reopen if this is not the case.

**Closed by Aerijo** 2018-04-09 12:18 UTC

**Comment by rammmiro** [comment] 2018-04-09 12:31
Thank you, it was the exact same issue. I checked open issues but not closed ones. Sorry for the inconvenience.

**Comment by Aerijo** [comment] 2018-04-09 12:32
Well that one was open. But I've changed the title to something more understandable.
