### ISSUE TITLE
Highligt of \cite does not work on long lines

### ISSUE THREAD

**Issue by frehage** [area/language-latex#188] opened 2018-07-24 10:24 UTC
### Prerequisites
- [x] Put an `X` in this box if you have done the following:
  - Ensured the issue has not already been raised
  - Ensured the issue is caused by this package
  - Run `atom --safe`, activated this package, and the issue persisted

### Description
There may only be a certain amount of characters that is part of \cite commands in a single line. After which the highlighting will stop working, both for the cited name and the cite command. 

The highlighting resumes on new \cite{} commands on the next line.

### Steps to reproduce & Minimum working example
1. Writing too many or too long citations

```
\cite{Lorem}\cite{ipsum}\cite{dolor}\cite{sit}\cite{amet,}\cite{consectetur}\cite{adipiscing}\cite{elit.}\cite{Sed}\cite{id}\cite{dapibus}\cite{ante.}
```

#### Expected behaviour
All \cite{name} commands should be highlighted properly.

#### Actual behaviour
Highlighting of \cite{name} commands stops abrubtly after a certain number of charcters in a single line.

**Comment by kylebarron** [comment] 2018-08-14 14:50
This is a limitation of Atom's regex parsing.

Duplicate of https://github.com/area/language-latex/issues/139

**Closed** 2018-09-23 09:53 UTC
