### ISSUE TITLE
Strange Syntax Highlighting 

### ISSUE THREAD

**Issue by Briffou** [area/language-latex#99] opened 2016-10-28 13:50 UTC
I have a strange behaviour with a specific sequence of text. Maybe this issue is somehow related to #61, but it's not obvious to me. I'm on fedora 24 (but I also tried on my mac) with atom 1.11.1 and when I type this specific line in atom 

```latex
Try to reproduce a bug, I put some math $x$ and some more $(\frac{1}{2},0)$ and some more $(\frac{1}{2},0)$ and a reference \ref{DN_sans_point} and another reference \ref{DN_sans_point} and again some math $(\frac{2}{3},0)$ and some math $x \geq \frac{1}{2}$ and I don't know why my text is in green now.
```

the end of the line appear in green in atom, while she should be in white. What is very strange, is that if I remove one math mode, for example the first $x$, everything works fine. Any ideas ?

![screenshot_20161026_153737](https://cloud.githubusercontent.com/assets/18452695/19808379/96229a58-9cf2-11e6-85e8-738c28666654.png)

**Comment by yudai-nkt** [comment] 2016-10-28 14:00
Your problem is not related to the aforementioned issue, but a duplicate of #88. It is Atom's limitation and the current workaround is to wrap the text at proper length.

**Closed by yudai-nkt** 2016-10-28 14:00 UTC
