### ISSUE TITLE
Applied on non tex files (.lhs)

### ISSUE THREAD

**Issue by estebanlan** [area/language-latex#93] opened 2016-10-18 11:31 UTC
I was working in an .lhs file (using language-haskell) and if I have language-latex enabled the $ and the `  affect the syntax coloring
<img width="388" alt="languagelatex" src="https://cloud.githubusercontent.com/assets/22002420/19475994/172c09ae-9537-11e6-9fd2-965e126bd167.PNG">

**Comment by yudai-nkt** [comment] 2016-10-18 11:47
This package does nothing about Haskell-related files. I've just installed [`language-haskell`](https://atom.io/packages/language-haskell) and tried your snippet, but the appearances are much the same. Is "Literate Haskell" grammar selected in your `.lhs` file?

```haskell
> data FieldElem = FE2 F2 | FE3 F3 | FE4 F4 | FE7 F7 deriving (Show,Ord,Eq)



> f :: Int -> Int -> FieldElem
> f k 2 = FE2 $ F2 k
> f k 3 = FE3 $ F3 k
> f k 4 = FE4 $ F4 k
```

__with `language-latex` enabled:__
![enabled](https://cloud.githubusercontent.com/assets/13291527/19476380/dcd4b4b2-9573-11e6-8186-78afc4bb2556.png)

__with `language-latex` disabled:__
![disabled](https://cloud.githubusercontent.com/assets/13291527/19476384/e4da3236-9573-11e6-9151-658372680b95.png)

**Comment by estebanlan** [comment] 2016-10-18 12:37
Checked it out, turns out it is only active when the code is not active (has a > at the beginning). Therefore, if in the non code part of an .lhs has a $ or a `, this happens. Toggled language-latex on and off and it solved the problem
<img width="241" alt="langua-latex" src="https://cloud.githubusercontent.com/assets/22002420/19477862/6b7e9ca2-9540-11e6-9ed7-15cfb4a8ab6d.png">

**Comment by yudai-nkt** [comment] 2016-10-18 13:17
OK, I could reproduce the problem. Although I'm not familiar with Literate Haskell or even Haskell itself (maybe the former is something related to literate programming?), it seems to be a probelm of `language-haskell` as it [contains](https://github.com/atom-haskell/language-haskell/search?utf8=%E2%9C%93&q=latex) some LaTeX-related code.

**Comment by yudai-nkt** [comment] 2016-10-18 15:57
As can be seen atom-haskell/language-haskell#93, the line `This is how this looks until I do this $` is invalid not only for LaTeX but for lhs2TeX also. Hence, we won't cope with this point. Please avoid using such invalid input or syntax.

Regarding the backtick, it's a duplicate of #87, which is also quite similar to #61. So I'll close this issue and please subscribe the threads above if you get interested in what's going on.

**Closed by yudai-nkt** 2016-10-18 15:57 UTC
