### ISSUE TITLE
Crash on tab complete

### ISSUE THREAD

**Issue by QuantumPhi** [area/language-latex#21] opened 2014-12-16 07:03 UTC
Example:
```
begin [+ tab]
```
expands to
```
\begin{env}

\end{env}
```
but the editor does not display input after entering text for ``env``.

**Comment by cedhuf** [comment] 2015-08-03 12:39
Hi,
Do you have more information about this ? I can't get the point. `begin +tab` work as expected for me.

**Comment by area** [comment] 2016-10-02 09:50
Unable to reproduce either, so closing.

**Closed by area** 2016-10-02 09:50 UTC
