### ISSUE TITLE
Syntax highlighting just stopping mid-paragraph...

### ISSUE THREAD

**Issue by nickeubank** [area/language-latex#154] opened 2017-10-18 21:46 UTC
Not sure what's going on! A few examples:

![screen shot 2017-10-18 at 4 45 30 pm](https://user-images.githubusercontent.com/9683693/31744276-d1bbfb2e-b423-11e7-800c-a43d2d2debd4.png)

![screen shot 2017-10-18 at 4 45 37 pm](https://user-images.githubusercontent.com/9683693/31744283-d4b56be4-b423-11e7-9b38-fcd3500f8dce.png)

![screen shot 2017-10-18 at 4 45 46 pm](https://user-images.githubusercontent.com/9683693/31744287-d77b62c0-b423-11e7-99ae-d9f64fd23b3a.png)

**Comment by Aerijo** [comment] 2017-10-19 11:59
I can't copy and paste text from an image :(

**Comment by nickeubank** [comment] 2017-10-19 17:18
Right! Sorry, wanted image so you could see coloring, but of course that's hard to work with. Here's some matching text:

\noindent Research on the politics of ethnicity is dominated by efforts to explain two prominent empirical regularities. First, across a broad range of regions and institutional contexts, ethnicity consistently achieves a high degree of political salience (e.g. \citep{Chandra:2007vc,Posner:2011ta,Basedau:2011jt,Keefer:2009wu,Laitin:1998wp,Horowitz:2011vj}). This is true not only in terms of political rhetoric, but also political party organization and voting behavior. And second, ethnically fragmented communities tend to experience worse development outcomes and low investment in public goods (e.g. \citep{Easterly:1997fh,Alesina:2010wi,Alesina:2005gy,Miguel:2005kg,Khwaja:2009uq,Habyarimana:2011wh}).

The validation of this assumption was by no means a forgone conclusion. Indeed, many other promising hypothesis aimed at explaining the salience of ethnicity and premised on what seemed obvious assumptions have struggled in the face of subsequent empirical interrogation. For example, the theory that ethnic coalitions reflect shared policy preferences, and so bad outcomes in ethnically fragmented communities stem from policy disagreements \citep{Alesina:2010wi} has been met with recent studies that show policy preferences do \emph{not} appear to vary dramatically across ethnic groups (e.g. \cite{Desmet:2015wk,Habyarimana:2009tj}. See \cite{Lieberman:2012jm} for a dissenting view.), and ethnic parties do not appear to be structured to maximize policy influence \citep{Keefer:2009wu}. The idea people simply care more about co-ethnics than non-coethnics \citep{Habyarimana:2009tj,Charness:2002wu,Chen:2009to} and under-invest in public goods that also benefit non-co-ethnics \citep{Ejdemyr:2015wt} also does not square with laboratory results that show participants in anonymous altruism games seem just as generous to co-ethnics as non-coethnics \citep{Habyarimana:2009tj,Berge:2016tw,Dionne:2014ga}. And finally, the idea that ethnicity is strategically valuable because the recognizability and immutability of ethnicity allow minimal winning coalitions to ensure new-comers do not sneak in to claim benefits \citep{Fearon:2011wa} has been challenged by evidence that in many African contexts ethnicity is not that easy to identify in strangers \citep{Habyarimana:2009tj,Casey:2016vc,Anonymous:2012ddd}.

**Comment by Aerijo** [comment] 2017-10-19 21:31
OK. It's what I thought. I'm closing this as a duplicate of #139, look there for the solution. Bear in mind that my suggestion for fixing this on the package end was determined not to be in line with a grammar package, so just stick to the suggested one.

**Closed by Aerijo** 2017-10-19 21:31 UTC

**Comment by nickeubank** [comment] 2017-10-19 21:34
Great! Thanks @Aerijo
