### ISSUE TITLE
Syntax highlighting bug: undetected exit from math-mode

### ISSUE THREAD

**Issue by timtro** [area/language-latex#94] opened 2016-10-20 19:22 UTC
For some reason, I have several paragraphs where the text colour doesn't return to normal after some inline math. Attached is an example with this text:

```latex
Given a \emph{control sequence}\index{Control sequence, $\cu^k$!set of} $\bigl\{\cu^0,\cu^1,\ldots,\cu^{N-1}\bigr\} \in U^{N}$ for $N\in\posInts$, we can forecast a corresponding (discrete) state-space trajectory $\qcu^k$ based on the model. Starting from an initial position $\q^0$, simply iterate~\eqref{eq:discreteModel} recursively, using a previously obtained value. That is, starting from $\q^0$ we obtain $\q^1 = \fd(\q^0, \cu^0)$, and then $\q^2 = \fd(\q^1, \cu^1)$, and so on until $\q^N = \fd(\q^{N-1}, \cu^{N-1})$. In this context, the integer $N$ is referred to as the \emph{prediction horizon}\index{Horizon, prediction}, or simply as \emph{the horizon.}
```

![image](https://cloud.githubusercontent.com/assets/329007/19574565/eb894ef8-96d8-11e6-9328-4303d324a45e.png)

**Comment by yudai-nkt** [comment] 2016-10-20 23:36
I think this is a duplicate of #88. It is not a fault of `language-latex` and wrapping the text at proper length should fix the problem.

```latex
Given a \emph{control sequence}\index{Control sequence, $\cu^k$!set of} $\bigl\{\cu^0,\cu^1,\ldots,\cu^{N-1}\bigr\} \in U^{N}$ for $N\in\posInts$, 
we can forecast a corresponding (discrete) state-space trajectory $\qcu^k$ based on the model.
Starting from an initial position $\q^0$, simply iterate~\eqref{eq:discreteModel} recursively, using a previously obtained value. 
That is, starting from $\q^0$ we obtain $\q^1 = \fd(\q^0, \cu^0)$, and then $\q^2 = \fd(\q^1, \cu^1)$, and so on until $\q^N = \fd(\q^{N-1}, \cu^{N-1})$.
In this context, the integer $N$ is referred to as the \emph{prediction horizon}\index{Horizon, prediction}, or simply as \emph{the horizon.}
```
![2016-10-21 8 21 33](https://cloud.githubusercontent.com/assets/13291527/19581602/23f62604-9769-11e6-99d3-cc1ec668bc24.png)

Let me know if I'm mistaken about your issue.

**Closed by yudai-nkt** 2016-10-20 23:36 UTC
