### ISSUE TITLE
Syntax Highlighting Bug

### ISSUE THREAD

**Issue by cortner** [area/language-latex#87] opened 2016-10-06 08:23 UTC
the following line messes up all subsequent syntax highlighting.

```
\DeclareGraphicsRule{.tif}{png}{.png}{`convert #1 `dirname #1`/`basename #1 .tif`.png}
```

<img width="655" alt="with" src="https://cloud.githubusercontent.com/assets/7688515/19145371/8e11de80-8ba6-11e6-85ea-c838586af30d.png">
<img width="702" alt="without" src="https://cloud.githubusercontent.com/assets/7688515/19145377/95b8e82c-8ba6-11e6-9a7f-7e586065a604.png">

**Comment by yudai-nkt** [comment] 2016-10-06 16:31
I think this is a kind of duplicate of #61 although there is a difference between `single` / `double`. I'm afraid to say we have not come up with a proper solution.

**Closed** 2017-08-07 10:43 UTC
