### ISSUE TITLE
Incorrect highlighting

### ISSUE THREAD

**Issue by lrp** [area/language-latex#11] opened 2014-04-15 00:59 UTC
Below is a block of latex that highlights incorrectly in.  Starting from $f_{\bfal}(t)$, everything is lime green. I thought the problem might be my tex'ing, so I checked in textmate2, where it highlights correctly.  Here it is:

We denote the parameters\footnote{For gravitational waves this includes $\mathcal{M}, \eta,\alpha,\delta,\iota\ldots$} of a single event by the bold $\bfth$.  In general we'll be discussing a collection of $N$ events, so the parameters of an individual event will have a subscript, $\bfth_n$, which the entire collection of events will be surrounded in curly braces and carry explicit upper and lower limits, e.g., $\bfthall$.  Our central problem will be to determine the distribution of some particular member of $\bfth$, which we will call\footnote{This notation should be better!} $t$. The data\footnote{$h(t)$ timeseries for gravitational waves} used to determine $\bfth$ is denoted $\bfD$, and so $\bfD_n$ and $\bfDall$ have the same meanings as their $\bfth$ counterparts.  Finally, we will call the distribution we are ultimately interested in determining where $f_{\bfal}(t)$, where $\bfal$ are the parameters of the distribution\footnote{E.g., mean and variance if the distribution is Gaussian.} and $t$, as before, is a parameter in $\bfth$.

**Comment by cedhuf** [comment] 2015-08-03 13:54
Duplicate of https://github.com/area/language-latex/issues/13.

**Closed by cedhuf** 2015-08-03 13:54 UTC
