### ISSUE TITLE
Weird highlight for some text

### ISSUE THREAD

**Issue by Towdium** [area/language-latex#100] opened 2016-10-29 14:32 UTC
For most of the text, it works perfectly. But for the following text, the highlight seems a little weird. The text is given as follows:

```LaTeX
Figure \ref{rin} shows the input characteristics of BC109 transistor\footnote{Acquired using PSpice}. When input current is about \SI{18}{\micro A}, which is the base current in DC analysis, the value of $R_\pi$ is about \SI{2.1}{k\ohm}. Since $v_{in} = R_\pi i_b$, it can be acquired $v_{in, \text{MAX}} = \SI{62.1}{mV}$ and $v_{in, \text{MIN}} = \SI{-38.0}{mV}$. However, since the input current varies in a large range, there exist a large uncertainty in the value of $r_\pi$, especially for the trough of input signal, leading to a low input current and a small $r_\pi$. Therefore, at the peak of output signal, the amplification factor might not be as large as expected. Generally speaking, the result is corresponding to the result within range of error.
```

The highlight result is:
![text](https://cloud.githubusercontent.com/assets/10866568/19830272/05deed70-9dec-11e6-8242-f4101406a30b.png)

Using Monokai syntax theme, but will happen for nearly all of the syntax themes.
Happening on both Windows and Linux.

**Comment by yudai-nkt** [comment] 2016-10-29 14:36
Closing the issue as this is a duplicate of #88 and some others. It is Atom's limitation and the current workaround is to wrap the text at proper length.

**Closed by yudai-nkt** 2016-10-29 14:36 UTC
